name: Test Secrets
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test_sheets
        env:
          GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
        run: python test.py
      # - name: Print secret
      #   run: echo "Secret is ${{ secrets.GOOGLE_SHEETS_CREDS }}"5