steps:
  - name: My step
    env:
      GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
    run: python test_sheets.py

name: Test Secrets
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: echo "Secret is ${{ secrets.GOOGLE_SHEETS_CREDS }}"